// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package scarab

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerClient interface {
	RegisterProfile(ctx context.Context, in *RegisterProfileRequest, opts ...grpc.CallOption) (Manager_RegisterProfileClient, error)
}

type managerClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerClient(cc grpc.ClientConnInterface) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) RegisterProfile(ctx context.Context, in *RegisterProfileRequest, opts ...grpc.CallOption) (Manager_RegisterProfileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Manager_ServiceDesc.Streams[0], "/scarab.Manager/RegisterProfile", opts...)
	if err != nil {
		return nil, err
	}
	x := &managerRegisterProfileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Manager_RegisterProfileClient interface {
	Recv() (*KeepAlive, error)
	grpc.ClientStream
}

type managerRegisterProfileClient struct {
	grpc.ClientStream
}

func (x *managerRegisterProfileClient) Recv() (*KeepAlive, error) {
	m := new(KeepAlive)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ManagerServer is the server API for Manager service.
// All implementations must embed UnimplementedManagerServer
// for forward compatibility
type ManagerServer interface {
	RegisterProfile(*RegisterProfileRequest, Manager_RegisterProfileServer) error
	mustEmbedUnimplementedManagerServer()
}

// UnimplementedManagerServer must be embedded to have forward compatible implementations.
type UnimplementedManagerServer struct {
}

func (UnimplementedManagerServer) RegisterProfile(*RegisterProfileRequest, Manager_RegisterProfileServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterProfile not implemented")
}
func (UnimplementedManagerServer) mustEmbedUnimplementedManagerServer() {}

// UnsafeManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServer will
// result in compilation errors.
type UnsafeManagerServer interface {
	mustEmbedUnimplementedManagerServer()
}

func RegisterManagerServer(s grpc.ServiceRegistrar, srv ManagerServer) {
	s.RegisterService(&Manager_ServiceDesc, srv)
}

func _Manager_RegisterProfile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterProfileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServer).RegisterProfile(m, &managerRegisterProfileServer{stream})
}

type Manager_RegisterProfileServer interface {
	Send(*KeepAlive) error
	grpc.ServerStream
}

type managerRegisterProfileServer struct {
	grpc.ServerStream
}

func (x *managerRegisterProfileServer) Send(m *KeepAlive) error {
	return x.ServerStream.SendMsg(m)
}

// Manager_ServiceDesc is the grpc.ServiceDesc for Manager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Manager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scarab.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterProfile",
			Handler:       _Manager_RegisterProfile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scarab.proto",
}

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerClient interface {
	ReportLoad(ctx context.Context, in *ReportLoadRequest, opts ...grpc.CallOption) (Worker_ReportLoadClient, error)
	RunProfile(ctx context.Context, opts ...grpc.CallOption) (Worker_RunProfileClient, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) ReportLoad(ctx context.Context, in *ReportLoadRequest, opts ...grpc.CallOption) (Worker_ReportLoadClient, error) {
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], "/scarab.Worker/ReportLoad", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerReportLoadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Worker_ReportLoadClient interface {
	Recv() (*LoadMetrics, error)
	grpc.ClientStream
}

type workerReportLoadClient struct {
	grpc.ClientStream
}

func (x *workerReportLoadClient) Recv() (*LoadMetrics, error) {
	m := new(LoadMetrics)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerClient) RunProfile(ctx context.Context, opts ...grpc.CallOption) (Worker_RunProfileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[1], "/scarab.Worker/RunProfile", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerRunProfileClient{stream}
	return x, nil
}

type Worker_RunProfileClient interface {
	Send(*RunProfileRequest) error
	Recv() (*JobMetrics, error)
	grpc.ClientStream
}

type workerRunProfileClient struct {
	grpc.ClientStream
}

func (x *workerRunProfileClient) Send(m *RunProfileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workerRunProfileClient) Recv() (*JobMetrics, error) {
	m := new(JobMetrics)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility
type WorkerServer interface {
	ReportLoad(*ReportLoadRequest, Worker_ReportLoadServer) error
	RunProfile(Worker_RunProfileServer) error
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (UnimplementedWorkerServer) ReportLoad(*ReportLoadRequest, Worker_ReportLoadServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportLoad not implemented")
}
func (UnimplementedWorkerServer) RunProfile(Worker_RunProfileServer) error {
	return status.Errorf(codes.Unimplemented, "method RunProfile not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_ReportLoad_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportLoadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).ReportLoad(m, &workerReportLoadServer{stream})
}

type Worker_ReportLoadServer interface {
	Send(*LoadMetrics) error
	grpc.ServerStream
}

type workerReportLoadServer struct {
	grpc.ServerStream
}

func (x *workerReportLoadServer) Send(m *LoadMetrics) error {
	return x.ServerStream.SendMsg(m)
}

func _Worker_RunProfile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).RunProfile(&workerRunProfileServer{stream})
}

type Worker_RunProfileServer interface {
	Send(*JobMetrics) error
	Recv() (*RunProfileRequest, error)
	grpc.ServerStream
}

type workerRunProfileServer struct {
	grpc.ServerStream
}

func (x *workerRunProfileServer) Send(m *JobMetrics) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workerRunProfileServer) Recv() (*RunProfileRequest, error) {
	m := new(RunProfileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scarab.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportLoad",
			Handler:       _Worker_ReportLoad_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunProfile",
			Handler:       _Worker_RunProfile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "scarab.proto",
}
